CREATE TABLE [DW].[DateTimeDim] (
  [DateKey] datetime PRIMARY KEY,
  [FullDateAlternateKey] date,
  [PersianFullDateAlternateKey] date,
  [DayNumberOfWeek] int,
  [PersianDayNumberOfWeek] int,
  [EnglishDayNameOfWeek] nvarchar(255),
  [PersianDayNameOfWeek] nvarchar(255),
  [DayNumberOfMonth] int,
  [PersianDayNumberOfMonth] int,
  [DayNumberOfYear] int,
  [PersianDayNumberOfYear] int,
  [WeekNumberOfYear] int,
  [PersianWeekNumberOfYear] int,
  [EnglishMonthName] nvarchar(255),
  [PersianMonthName] nvarchar(255),
  [MonthNumberOfYear] int,
  [PersianMonthNumberOfYear] int,
  [CalendarQuarter] int,
  [PersianCalendarQuarter] int,
  [CalendarYear] int,
  [PersianCalendarYear] int,
  [CalendarSemester] int,
  [PersianCalendarSemester] int,
  [Business_Day_YN] BIT,
  [Time] time,
  [Hour] int,
  [Minute] int
)
GO
