Initial_Account_Dim
Initial_Aircraft_Dim
Initial_Airline_Dim
Initial_AirlineAirportService_Dim
Initial_Airport_Dim
Initial_Crew_Dim
Initial_Date_Dim
Initial_DateTime_Dim
Initial_Flightt_Dim
Initial_LoyaltyTier_Dim
Initial_LoyaltyTransactionType_Dim
Initial_Payment_Dim
Initial_Person_Dim
Initial_PointConversionRate_Dim --should be implemented
Initial_ServiceOffering_Dim --should be implemented